spring:
  application:
    name:Address Book Application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/address_book_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: rituraj1810.be21@chitkara.edu.in
    password: your_email_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

